# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 56d33c8158a91259e963d1c75321d04c53c5f6d0a730ba14abdadf708c32a6964ee819610dbf6a093e0f2d99d09579d65ffe7eb27dd0b49514e76598c23100e1

test:
  secret_key_base: c79a110110e327cae3a4964bc88582175dccd148006e8f64e81e6a82e3a68e7fa711062ec3dde4085857e4b191e9ebbe260400c8a21cf04dc29287de37ced466

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
